Repository KengoKudou/Nihenihe_Movie, pull requests merged in 2022-09, with the labels that each got.

#67 お気に入り動画の登録処理
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Random/RandomLogoController.php
  app/Http/Controllers/Random/RandomPath.php
  app/Http/Controllers/Random/RandomTagController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/Video/GetAllTagsController.php
  app/Http/Controllers/Video/MyListController.php
  app/Http/Controllers/Video/UploadController.php
  app/Http/Controllers/Video/VideoController.php
  app/Http/Controllers/Video/VideoTimeController.php
  app/Http/Controllers/VideoLinkController.php
  app/Models/Artwork.php
  app/Models/MyList.php
  app/Models/UsersComment.php
  database/migrations/2022_07_27_100324_create_artwork_tags_table.php
  database/migrations/2022_09_12_100833_create_my_lists_table.php
  database/seeders/ArtworkTableSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/MyListSeeder.php
  database/seeders/UsersTableSeeder.php
  public/css/add.css
  public/css/heart.css
  public/css/main.css
  public/js/likeButton.js
  resources/views/add/portfolio_kudou.blade.php
  resources/views/add/portfolio_nishigata.blade.php
  resources/views/add/portfolio_ura_nishigata.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/header.blade.php
  resources/views/layouts/header_channel.blade.php
  resources/views/layouts/header_tag.blade.php
  resources/views/search/search_channel.blade.php
  resources/views/search/search_channel_list.blade.php
  resources/views/search/search_tag.blade.php
  resources/views/search/search_video.blade.php
  resources/views/search/search_video_list.blade.php
  resources/views/video/my_list.blade.php
  resources/views/video/video.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: bug, enhancement

#68 feature/mylist
  resources/views/welcome.blade.php
Labels: bug

#69 お気に入り動画表示可能
  app/Http/Controllers/Video/MyListController.php
  app/Models/MyList.php
  routes/web.php
Labels: enhancement

#70 artwork_tagテーブルの修正
  database/migrations/2022_07_27_100324_create_artwork_tags_table.php
Labels: bug
